### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by zacice** [ldesgoui/user.js#1]
I am dumb and don't know what I am doing. https://imgur.com/a/WCIrU

**Comment by Martii** [comment]
https://openuserjs.org/about/Tampermonkey-for-Chrome#installing-tampermonkey or https://openuserjs.org/about/Violentmonkey-for-Chrome#installing-violentmonkey

Native Chromes Userscript'ing is pretty bad... so use Tampermonkey *(TM)* or Violentmonkey *(VM)*

**Comment by ldesgoui** [comment]
Sorry, I somehow didn't have notifications on this repo.
I assume you've figured out by now, the comment above is right.
They're also listed here: https://openuserjs.org/users/ldesgoui/scripts
